import { Experience } from './types'

export const experienceData: Experience[] = [
  {
    id: 'skuratov',
    company: 'Skuratov Coffee',
    position: 'experience.skuratov.position',
    period: 'experience.skuratov.period',
    description: 'experience.skuratov.description',
    responsibilities: [
      'experience.skuratov.responsibilities.0',
      'experience.skuratov.responsibilities.1',
      'experience.skuratov.responsibilities.2',
      'experience.skuratov.responsibilities.3',
      'experience.skuratov.responsibilities.4',
      'experience.skuratov.responsibilities.5',
      'experience.skuratov.responsibilities.6',
      'experience.skuratov.responsibilities.7',
      'experience.skuratov.responsibilities.8',
      'experience.skuratov.responsibilities.9',
      'experience.skuratov.responsibilities.10',
      'experience.skuratov.responsibilities.11',
    ],
    achievements: [
      'experience.skuratov.achievements.0',
      'experience.skuratov.achievements.1',
      'experience.skuratov.achievements.2',
      'experience.skuratov.achievements.3',
      'experience.skuratov.achievements.4',
      'experience.skuratov.achievements.5',
      'experience.skuratov.achievements.6',
    ],
    technologies: [
      'Next.js',
      'TypeScript',
      'Redux Toolkit',
      'SCSS',
      'React Hook Form',
      'React Router',
      'Docker',
    ],
    team: {
      frontend: 3,
      backend: 2,
      designer: 2,
      manager: 1,
    },
  },
  {
    id: 'condition',
    company: 'Condition Tea',
    position: 'experience.condition.position',
    period: 'experience.condition.period',
    description: 'experience.condition.description',
    responsibilities: [
      'experience.condition.responsibilities.0',
      'experience.condition.responsibilities.1',
      'experience.condition.responsibilities.2',
      'experience.condition.responsibilities.3',
      'experience.condition.responsibilities.4',
      'experience.condition.responsibilities.5',
      'experience.condition.responsibilities.6',
      'experience.condition.responsibilities.7',
      'experience.condition.responsibilities.8',
      'experience.condition.responsibilities.9',
    ],
    achievements: [
      'experience.condition.achievements.0',
      'experience.condition.achievements.1',
      'experience.condition.achievements.2',
      'experience.condition.achievements.3',
      'experience.condition.achievements.4',
      'experience.condition.achievements.5',
    ],
    technologies: [
      'React',
      'TypeScript',
      'Redux Toolkit',
      'SCSS',
      'React Hook Form',
      'Axios',
      'Go',
      'Docker',
    ],
    team: {
      frontend: 2,
      backend: 1,
      designer: 1,
      manager: 1,
    },
  },
  {
    id: 'usti',
    company: 'USTI YogaFlow',
    position: 'experience.usti.position',
    period: 'experience.usti.period',
    description: 'experience.usti.description',
    responsibilities: [
      'experience.usti.responsibilities.0',
      'experience.usti.responsibilities.1',
      'experience.usti.responsibilities.2',
      'experience.usti.responsibilities.3',
      'experience.usti.responsibilities.4',
      'experience.usti.responsibilities.5',
      'experience.usti.responsibilities.6',
      'experience.usti.responsibilities.7',
    ],
    achievements: [
      'experience.usti.achievements.0',
      'experience.usti.achievements.1',
      'experience.usti.achievements.2',
      'experience.usti.achievements.3',
      'experience.usti.achievements.4',
      'experience.usti.achievements.5',
    ],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Redux Toolkit',
      'Tailwind CSS',
      'Framer Motion',
      'Nest.js',
      'Docker',
    ],
    team: {
      frontend: 2,
      backend: 2,
      designer: 1,
      manager: 1,
    },
  },
  {
    id: 'lzmedia',
    company: 'LZ.MEDIA RecordFitnes',
    position: 'experience.lzmedia.position',
    period: 'experience.lzmedia.period',
    description: 'experience.lzmedia.description',
    responsibilities: [
      'experience.lzmedia.responsibilities.0',
      'experience.lzmedia.responsibilities.1',
      'experience.lzmedia.responsibilities.2',
      'experience.lzmedia.responsibilities.3',
      'experience.lzmedia.responsibilities.4',
      'experience.lzmedia.responsibilities.5',
    ],
    achievements: [
      'experience.lzmedia.achievements.0',
      'experience.lzmedia.achievements.1',
      'experience.lzmedia.achievements.2',
      'experience.lzmedia.achievements.3',
      'experience.lzmedia.achievements.4',
      'experience.lzmedia.achievements.5',
    ],
    technologies: [
      'React',
      'TypeScript',
      'Redux Toolkit',
      'SCSS',
      'React Hook Form',
      'Python',
      'Docker',
    ],
    team: {
      frontend: 1,
      backend: 1,
      designer: 1,
      manager: 1,
    },
  },
]
