import { Achievement } from './types'

export const achievementsData: Achievement[] = [
  {
    id: 'skuratov-platform',
    title: 'achievements.skuratov.title',
    issuer: 'achievements.skuratov.issuer',
    date: '2024-2025',
    description: 'achievements.skuratov.description',
    image: '/images/achievements/skuratov.svg',
    skills: ['Next.js', 'TypeScript', 'Redux Toolkit', 'Gamification', 'CI/CD'],
  },
  {
    id: 'condition-ecommerce',
    title: 'achievements.condition.title',
    issuer: 'achievements.condition.issuer',
    date: '2023-2024',
    description: 'achievements.condition.description',
    image: '/images/achievements/condition.svg',
    skills: ['React', 'TypeScript', 'Go Integration', 'E-commerce', 'Analytics'],
  },
  {
    id: 'yoga-booking',
    title: 'achievements.usti.title',
    issuer: 'achievements.usti.issuer',
    date: '2023',
    description: 'achievements.usti.description',
    image: '/images/achievements/yoga.svg',
    skills: ['Next.js', 'Nest.js', 'Docker', 'Payment Integration', 'SEO'],
  },
  {
    id: 'architecture',
    title: 'achievements.architecture.title',
    issuer: 'achievements.architecture.issuer',
    date: '2024',
    description: 'achievements.architecture.description',
    image: '/images/achievements/architecture.svg',
    skills: ['FSD', 'Clean Architecture', 'SOLID', 'Design Patterns'],
  },
  {
    id: 'performance',
    title: 'achievements.performance.title',
    issuer: 'achievements.performance.issuer',
    date: '2021-2025',
    description: 'achievements.performance.description',
    image: '/images/achievements/performance.svg',
    skills: ['Lighthouse', 'Code Splitting', 'Lazy Loading', 'Bundle Analysis'],
  },
  {
    id: 'typescript-mastery',
    title: 'achievements.typescript.title',
    issuer: 'achievements.typescript.issuer',
    date: '2022-2025',
    description: 'achievements.typescript.description',
    image: '/images/achievements/typescript.svg',
    skills: ['TypeScript', 'Generics', 'Type Safety', 'Advanced Types'],
  },
  {
    id: 'testing',
    title: 'achievements.testing.title',
    issuer: 'achievements.testing.issuer',
    date: '2022-2025',
    description: 'achievements.testing.description',
    image: '/images/achievements/testing.svg',
    skills: ['Jest', 'Vitest', 'React Testing Library', 'E2E Testing'],
  },
  {
    id: 'creative-cluster',
    title: 'achievements.community.title',
    issuer: 'achievements.community.issuer',
    date: '2023-2025',
    description: 'achievements.community.description',
    image: '/images/achievements/community.svg',
    skills: ['Event Management', 'Community Building', 'Leadership'],
  },
]